export const divisions = [
  'Dhaka', 'Chittagong', 'Rajshahi', 'Khulna', 'Barisal', 'Sylhet', 'Rangpur', 'Mymensingh'
];

export const districtsByDivision = {
  Dhaka: ['Dhaka', 'Faridpur', 'Gazipur', 'Gopalganj', 'Kishoreganj', 'Madaripur', 'Manikganj', 'Munshiganj', 'Narayanganj', 'Narsingdi', 'Rajbari', 'Shariatpur', 'Tangail'],
  Chittagong: ['Bandarban', 'Brahmanbaria', 'Chandpur', 'Chittagong', 'Comilla', 'Cox\'s Bazar', 'Feni', 'Khagrachhari', 'Lakshmipur', 'Noakhali', 'Rangamati'],
  Rajshahi: ['Bogra', 'Chapainawabganj', 'Joypurhat', 'Naogaon', 'Natore', 'Nawabganj', 'Pabna', 'Rajshahi', 'Sirajganj'],
  Khulna: ['Bagerhat', 'Chuadanga', 'Jessore', 'Jhenaidah', 'Khulna', 'Kushtia', 'Magura', 'Meherpur', 'Narail', 'Satkhira'],
  Barisal: ['Barguna', 'Barisal', 'Bhola', 'Jhalokati', 'Patuakhali', 'Pirojpur'],
  Sylhet: ['Habiganj', 'Moulvibazar', 'Sunamganj', 'Sylhet'],
  Rangpur: ['Dinajpur', 'Gaibandha', 'Kurigram', 'Lalmonirhat', 'Nilphamari', 'Panchagarh', 'Rangpur', 'Thakurgaon'],
  Mymensingh: ['Jamalpur', 'Mymensingh', 'Netrokona', 'Sherpur']
};

export const upazilasByDistrict = {
  Dhaka: ['Dhanmondi', 'Gulshan', 'Mirpur', 'Mohammadpur', 'Motijheel', 'Pallabi', 'Ramna', 'Tejgaon', 'Uttara', 'Bashabo', 'Jatrabari', 'Khilgaon', 'Savar', 'Dhamrai', 'Keraniganj', 'Nawabganj', 'DOHS'],
  Faridpur: ['Faridpur Sadar', 'Boalmari', 'Alfadanga', 'Sadarpur', 'Nagarkanda', 'Bhanga', 'Charbhadrashan', 'Saltha'],
  Gazipur: ['Gazipur Sadar', 'Kaliakair', 'Sreepur', 'Kaliganj', 'Kapasia', 'Joydebpur'],
  Gopalganj: ['Gopalganj Sadar', 'Kashiani', 'Muksudpur', 'Tungipara', 'Kotalipara'],
  Kishoreganj: ['Kishoreganj Sadar', 'Bajitpur', 'Bhairab', 'Hossainpur', 'Itna', 'Mithamain', 'Austagram', 'Karimganj', 'Katiadi', 'Pakundia'],
  Madaripur: ['Madaripur Sadar', 'Shibchar', 'Rajoir', 'Kalkini'],
  Manikganj: ['Manikganj Sadar', 'Singair', 'Saturia', 'Daulatpur', 'Ghior', 'Harirampur', 'Shivalaya'],
  Munshiganj: ['Munshiganj Sadar', 'Sreenagar', 'Sirajdikhan', 'Lohajang', 'Gazaria', 'Tongibari'],
  Narayanganj: ['Narayanganj Sadar', 'Bandar', 'Araihazar', 'Sonargaon', 'Rupganj'],
  Narsingdi: ['Narsingdi Sadar', 'Belabo', 'Monohardi', 'Raipura', 'Shibpur', 'Palash'],
  Rajbari: ['Rajbari Sadar', 'Pangsha', 'Balia', 'Goaland'],
  Shariatpur: ['Shariatpur Sadar', 'Damudya', 'Naria', 'Bhedarganj', 'Palong', 'Gosairhat'],
  Tangail: ['Tangail Sadar', 'Mirzapur', 'Dhanbari', 'Kalihati', 'Nagarpur', 'Sakhipur', 'Ghatail', 'Modhupur', 'Basail', 'Delduar'],
  Bandarban: ['Bandarban Sadar', 'Lama', 'Naikhongchhari', 'Ali Kadam', 'Rowangchhari', 'Ruma', 'Thanchi'],
  Brahmanbaria: ['Brahmanbaria Sadar', 'Ashuganj', 'Nasirnagar', 'Sarail', 'Kasba', 'Akhaihaur', 'Banchharampur', 'Nabinagar', 'Bijoynagar'],
  Chandpur: ['Chandpur Sadar', 'Haimchar', 'Faridganj', 'Matlab', 'Chhagalnaiya', 'Shahrasti', 'Kachua'],
  Chittagong: ['Chittagong Sadar', 'Pahartali', 'Panchlaish', 'Patenga', 'Double Mooring', 'EPZ', 'Anwara', 'Banshkhali', 'Fatikchhari', 'Hathazari', 'Karnaphuli', 'Lohagara', 'Mirsharai', 'Raozan', 'Sandwip', 'Sitakunda', 'Rangunia', 'Boalkhali'],
  Comilla: ['Comilla Sadar', 'Comilla Adarsha', 'Barura', 'Burichang', 'Chauddagram', 'Daudkandi', 'Debidwar', 'Homna', 'Laksam', 'Monohorgonj', 'Meghna', 'Muradnagar', 'Nangalkot', 'Titas', 'Chandina'],
  'Cox\'s Bazar': ['Cox\'s Bazar Sadar', 'Chakaria', 'Kutubdia', 'Maheshkhali', 'Ramu', 'Teknaf', 'Ukhia', 'Pekua'],
  Feni: ['Feni Sadar', 'Chhagalnaiya', 'Daganbhuiyan', 'Fulgazi', 'Parshuram', 'Sonagazi'],
  Khagrachhari: ['Khagrachhari Sadar', 'Dighinala', 'Lakshmichhari', 'Mahalchhari', 'Manikchhari', 'Matiranga', 'Panchhari', 'Ramgarh'],
  Lakshmipur: ['Lakshmipur Sadar', 'Raipur', 'Ramganj', 'Ramgati', 'Kamalnagar'],
  Noakhali: ['Noakhali Sadar', 'Subarnachar', 'Companiganj', 'Begumganj', 'Chatkhil', 'Hatiya', 'Senbagh', 'Sonaimuri', 'Kabirhat'],
  Rangamati: ['Rangamati Sadar', 'Kaptai', 'Belaichari', 'Barkal', 'Juraichari', 'Naniarchar', 'Rajasthali', 'Longadu', 'Naniarchar'],
  Bogra: ['Bogra Sadar', 'Shajahanpur', 'Sariakandi', 'Dhunat', 'Dhupchanchia', 'Gabtali', 'Sherpur', 'Shibganj', 'Sonatala', 'Kahalu', 'Adamdighi'],
  Chapainawabganj: ['Chapainawabganj Sadar', 'Shibganj', 'Gomastapur', 'Nachole', 'Bholahat'],
  Joypurhat: ['Joypurhat Sadar', 'Akkelpur', 'Kalai', 'Khetlal', 'Panchbibi'],
  Naogaon: ['Naogaon Sadar', 'Atrai', 'Badalgachhi', 'Dhamoirhat', 'Manda', 'Mohadevpur', 'Patnitala', 'Porsha', 'Sapahar', 'Raninagar', 'Niamatpur'],
  Natore: ['Natore Sadar', 'Bagatipara', 'Baraigram', 'Gurudaspur', 'Lalpur', 'Singra'],
  Nawabganj: ['Nawabganj Sadar', 'Shibganj', 'Bholahat'],
  Pabna: ['Pabna Sadar', 'Atgharia', 'Bera', 'Bhangura', 'Chatmohar', 'Faridpur', 'Ishwardi', 'Santhia', 'Sujanagar'],
  Rajshahi: ['Rajshahi Sadar', 'Boalia', 'Rajpara', 'Shah Makdam', 'Motihar', 'Paba', 'Puthia', 'Durgapur', 'Bagmara', 'Tanore', 'Charghat', 'Bagha', 'Godagari'],
  Sirajganj: ['Sirajganj Sadar', 'Belkuchi', 'Chauhali', 'Kamarkhanda', 'Kazipur', 'Raiganj', 'Shahjadpur', 'Tarash', 'Ullahpara'],
  Bagerhat: ['Bagerhat Sadar', 'Chitalmagar', 'Fakirhat', 'Kachua', 'Mollahat', 'Mongla', 'Morrelganj', 'Rampal', 'Sarankhola'],
  Chuadanga: ['Chuadanga Sadar', 'Alamdanga', 'Damurhuda', 'Jibannagar'],
  Jessore: ['Jessore Sadar', 'Abhaynagar', 'Bagherpara', 'Chaugachha', 'Jhikargachha', 'Keshabpur', 'Manirampur', 'Sharsha'],
  Jhenaidah: ['Jhenaidah Sadar', 'Harinakunda', 'Kaliganj', 'Kotchandpur', 'Moheshpur', 'Shailkupa'],
  Khulna: ['Khulna Sadar', 'Dighalia', 'Dumuria', 'Koyra', 'Paikgachha', 'Phultala', 'Rupsa', 'Terokhada', 'Batiaghata', 'Dacope'],
  Kushtia: ['Kushtia Sadar', 'Bheramara', 'Daulatpur', 'Khoksa', 'Kumarkhali', 'Mirpur'],
  Magura: ['Magura Sadar', 'Shalikha', 'Sreepur', 'Muhammadpur'],
  Meherpur: ['Meherpur Sadar', 'Gangni', 'Mujibnagar'],
  Narail: ['Narail Sadar', 'Kalia', 'Lohagara'],
  Satkhira: ['Satkhira Sadar', 'Assasuni', 'Debhata', 'Kalaroa', 'Kaliganj', 'Shyamnagar', 'Tala'],
  Barguna: ['Barguna Sadar', 'Amtali', 'Bamna', 'Betagi', 'Patharghata', 'Taltali'],
  Barisal: ['Barisal Sadar', 'Agailjhara', 'Babuganj', 'Bakerganj', 'Banaripara', 'Gaurnadi', 'Hizla', 'Mehendiganj', 'Muladi', 'Wazirpur'],
  Bhola: ['Bhola Sadar', 'Burhanuddin', 'Char Fasson', 'Daulatkhan', 'Lalmohan', 'Manpura', 'Tazumuddin'],
  Jhalokati: ['Jhalokati Sadar', 'Kathalia', 'Nalchity', 'Rajapur'],
  Patuakhali: ['Patuakhali Sadar', 'Bauphal', 'Dashmina', 'Dumki', 'Galachipa', 'Kalapara', 'Mirzaganj', 'Rangabali'],
  Pirojpur: ['Pirojpur Sadar', 'Bhandaria', 'Kawkhali', 'Mathbaria', 'Nazirpur', 'Nesarabad (Swarupkati)'],
  Habiganj: ['Habiganj Sadar', 'Ajmiriganj', 'Baniachong', 'Bahubal', 'Chunarughat', 'Lakhai', 'Madhabpur', 'Nabiganj', 'Shaistaganj'],
  Moulvibazar: ['Moulvibazar Sadar', 'Barlekha', 'Juri', 'Kamalganj', 'Kulaura', 'Rajnagar', 'Sreemangal'],
  Sunamganj: ['Sunamganj Sadar', 'Bishwamvarpur', 'Chhatak', 'Dakshin Sunamganj', 'Derai', 'Dharampasha', 'Dowarabazar', 'Jagannathpur', 'Jamalganj', 'Sulla', 'Tahirpur'],
  Sylhet: ['Sylhet Sadar', 'Balaganj', 'Beanibazar', 'Bishwanath', 'Companiganj', 'Dakshin Surma', 'Fenchuganj', 'Golapganj', 'Gowainghat', 'Jaintiapur', 'Kanaighat', 'Osmani Nagar', 'Zakiganj'],
  Dinajpur: ['Dinajpur Sadar', 'Birampur', 'Birganj', 'Biral', 'Bochaganj', 'Chirirbandar', 'Fulbari', 'Ghoraghat', 'Hakimpur', 'Kaharole', 'Khansama', 'Nawabganj', 'Parbatipur'],
  Gaibandha: ['Gaibandha Sadar', 'Fulchhari', 'Gobindaganj', 'Palashbari', 'Sadullapur', 'Saghata', 'Sundarganj'],
  Kurigram: ['Kurigram Sadar', 'Bhurungamari', 'Char Rajibpur', 'Chilmari', 'Phulbari', 'Nageshwari', 'Rajarhat', 'Raomari', 'Ulipur'],
  Lalmonirhat: ['Lalmonirhat Sadar', 'Aditmari', 'Hatibandha', 'Kaliganj', 'Patgram'],
  Nilphamari: ['Nilphamari Sadar', 'Dimla', 'Domar', 'Jaldhaka', 'Kishoreganj', 'Saidpur'],
  Panchagarh: ['Panchagarh Sadar', 'Atwari', 'Boda', 'Debiganj', 'Tetulia'],
  Rangpur: ['Rangpur Sadar', 'Badarganj', 'Gangachara', 'Kaunia', 'Mithapukur', 'Pirgachha', 'Pirganj', 'Taraganj', 'Rangpur City'],
  Thakurgaon: ['Thakurgaon Sadar', 'Baliadangi', 'Haripur', 'Pirganj', 'Ranisankail'],
  Jamalpur: ['Jamalpur Sadar', 'Bakshiganj', 'Dewanganj', 'Islampur', 'Madarganj', 'Melandaha', 'Sarishabari'],
  Mymensingh: ['Mymensingh Sadar', 'Bhaluka', 'Dhobaura', 'Fulbaria', 'Gaffargaon', 'Gauripur', 'Haluaghat', 'Ishwarganj', 'Muktagachha', 'Nandail', 'Phulpur', 'Trishal', 'Tangail'],
  Netrokona: ['Netrokona Sadar', 'Barhatta', 'Durgapur', 'Kalmakanda', 'Kendua', 'Khaliajuri', 'Madan', 'Mohanganj', 'Purbadhala', 'Atpara'],
  Sherpur: ['Sherpur Sadar', 'Jhenaigati', 'Nakla', 'Nalitabari', 'Sreebardi']
};

export const serviceCategories = [
  { value: 'catering', icon: '🍽️' },
  { value: 'makeup_artist', icon: '💄' },
  { value: 'cosmetics', icon: '✨' },
  { value: 'kazi_office', icon: '📜' },
  { value: 'saree_shop', icon: '👗' },
  { value: 'jewelry', icon: '💍' },
  { value: 'photography', icon: '📸' },
  { value: 'videography', icon: '🎥' },
  { value: 'event_management', icon: '🎪' },
  { value: 'decoration', icon: '🎊' },
  { value: 'flower_shop', icon: '💐' },
  { value: 'car_rental', icon: '🚗' },
  { value: 'wedding_cards', icon: '💌' },
  { value: 'salon', icon: '💇' },
  { value: 'gift_shop', icon: '🎁' }
];