import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  bn: {
    home: 'হোম',
    profiles: 'প্রোফাইল',
    services: 'সেবা',
    login: 'লগইন',
    register: 'নিবন্ধন',
    search: 'অনুসন্ধান',
    hero_title: 'আপনার জীবনসঙ্গী খুঁজুন',
    hero_subtitle: 'বাংলাদেশের সবচেয়ে বিশ্বস্ত ম্যাট্রিমনিয়াল সেবা',
    featured_profiles: 'বৈশিষ্ট্যযুক্ত প্রোফাইল',
    wedding_services: 'বিবাহ সেবা',
    view_all: 'সব দেখুন',
    like: 'পছন্দ',
    liked: 'পছন্দ করা হয়েছে',
    matched: 'ম্যাচ হয়েছে!',
    age: 'বয়স',
    district: 'জেলা',
    religion: 'ধর্ম',
    occupation: 'পেশা',
    marital_status: 'বৈবাহিক অবস্থা',
    never_married: 'অবিবাহিত',
    divorced: 'বিবাহবিচ্ছিন্ন',
    widowed: 'বিধবা/বিপত্নীক',
    male: 'পুরুষ',
    female: 'মহিলা',
    name_bangla: 'বাংলায় নাম',
    name_english: 'ইংরেজিতে নাম',
    mobile: 'মোবাইল নম্বর',
    full_address: 'পূর্ণ ঠিকানা',
    division: 'বিভাগ',
    gender: 'লিঙ্গ',
    bio: 'নিজের সম্পর্কে',
    photo: 'প্রোফাইল ছবি',
    membership: 'সদস্যপদ',
    free: 'বিনামূল্যে',
    premium: 'প্রিমিয়াম',
    submit: 'জমা দিন',
    pending: 'অপেক্ষমান',
    approved: 'অনুমোদিত',
    rejected: 'প্রত্যাখ্যাত',
    dashboard: 'ড্যাশবোর্ড',
    my_profile: 'আমার প্রোফাইল',
    my_likes: 'আমার পছন্দ',
    my_matches: 'আমার ম্যাচ',
    notifications: 'বিজ্ঞপ্তি',
    admin_panel: 'এডমিন প্যানেল',
    approve: 'অনুমোদন',
    reject: 'প্রত্যাখ্যান',
    total_users: 'মোট ব্যবহারকারী',
    pending_profiles: 'অপেক্ষমান প্রোফাইল',
    pending_services: 'অপেক্ষমান সেবা',
    total_matches: 'মোট ম্যাচ',
    contact_info: 'যোগাযোগের তথ্য',
    premium_only: 'শুধুমাত্র প্রিমিয়াম সদস্যদের জন্য',
    submit_service: 'সেবা জমা দিন',
    business_name: 'ব্যবসার নাম',
    contact_person: 'যোগাযোগকারী ব্যক্তি',
    category: 'ক্যাটাগরি',
    description: 'বিবরণ',
    images: 'ছবিসমূহ',
    website: 'ওয়েবসাইট',
    filter: 'ফিল্টার',
    all: 'সব',
    catering: 'ক্যাটারিং',
    makeup_artist: 'মেকআপ আর্টিস্ট',
    cosmetics: 'প্রসাধনী',
    kazi_office: 'কাজী অফিস',
    saree_shop: 'শাড়ির দোকান',
    jewelry: 'জুয়েলারি',
    photography: 'ফটোগ্রাফি',
    videography: 'ভিডিওগ্রাফি',
    event_management: 'ইভেন্ট ম্যানেজমেন্ট',
    decoration: 'সাজসজ্জা',
    flower_shop: 'ফুলের দোকান',
    car_rental: 'গাড়ি ভাড়া',
    wedding_cards: 'বিবাহের কার্ড',
    salon: 'সেলুন',
    gift_shop: 'গিফট শপ',
    no_results: 'কোনো ফলাফল পাওয়া যায়নি',
    loading: 'লোড হচ্ছে...',
    profile_pending: 'আপনার প্রোফাইল অনুমোদনের অপেক্ষায়',
    profile_rejected: 'আপনার প্রোফাইল প্রত্যাখ্যান করা হয়েছে',
    edit_profile: 'প্রোফাইল সম্পাদনা',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    upazila: 'উপজেলা',
    logout: 'লগআউট',
    create_profile: 'প্রোফাইল তৈরি করুন',
    email: 'ইমেইল',
    browse_profiles: 'প্রোফাইল দেখুন',
    find_partner: 'জীবনসঙ্গী খুঁজুন',
    trusted_platform: 'বিশ্বস্ত প্ল্যাটফর্ম',
    all_services: 'সকল সেবা',
    view_profile: 'প্রোফাইল দেখুন',
    back: 'পেছনে',
    Islam: 'ইসলাম',
    Hindu: 'হিন্দু',
    Christian: 'খ্রিস্টান',
    Buddhist: 'বৌদ্ধ',
    Other: 'অন্যান্য',
  },
  en: {
    home: 'Home',
    profiles: 'Profiles',
    services: 'Services',
    login: 'Login',
    register: 'Register',
    search: 'Search',
    hero_title: 'Find Your Life Partner',
    hero_subtitle: "Bangladesh's Most Trusted Matrimonial Service",
    featured_profiles: 'Featured Profiles',
    wedding_services: 'Wedding Services',
    view_all: 'View All',
    like: 'Like',
    liked: 'Liked',
    matched: 'Matched!',
    age: 'Age',
    district: 'District',
    religion: 'Religion',
    occupation: 'Occupation',
    marital_status: 'Marital Status',
    never_married: 'Never Married',
    divorced: 'Divorced',
    widowed: 'Widowed',
    male: 'Male',
    female: 'Female',
    name_bangla: 'Name (Bangla)',
    name_english: 'Name (English)',
    mobile: 'Mobile Number',
    full_address: 'Full Address',
    division: 'Division',
    gender: 'Gender',
    bio: 'About Yourself',
    photo: 'Profile Photo',
    membership: 'Membership',
    free: 'Free',
    premium: 'Premium',
    submit: 'Submit',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    dashboard: 'Dashboard',
    my_profile: 'My Profile',
    my_likes: 'My Likes',
    my_matches: 'My Matches',
    notifications: 'Notifications',
    admin_panel: 'Admin Panel',
    approve: 'Approve',
    reject: 'Reject',
    total_users: 'Total Users',
    pending_profiles: 'Pending Profiles',
    pending_services: 'Pending Services',
    total_matches: 'Total Matches',
    contact_info: 'Contact Info',
    premium_only: 'Premium Members Only',
    submit_service: 'Submit Service',
    business_name: 'Business Name',
    contact_person: 'Contact Person',
    category: 'Category',
    description: 'Description',
    images: 'Images',
    website: 'Website',
    filter: 'Filter',
    all: 'All',
    catering: 'Catering',
    makeup_artist: 'Makeup Artist',
    cosmetics: 'Cosmetics',
    kazi_office: 'Kazi Office',
    saree_shop: 'Saree Shop',
    jewelry: 'Jewelry',
    photography: 'Photography',
    videography: 'Videography',
    event_management: 'Event Management',
    decoration: 'Decoration',
    flower_shop: 'Flower Shop',
    car_rental: 'Car Rental',
    wedding_cards: 'Wedding Cards',
    salon: 'Salon',
    gift_shop: 'Gift Shop',
    no_results: 'No results found',
    loading: 'Loading...',
    profile_pending: 'Your profile is pending approval',
    profile_rejected: 'Your profile has been rejected',
    edit_profile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    upazila: 'Upazila',
    logout: 'Logout',
    create_profile: 'Create Profile',
    email: 'Email',
    browse_profiles: 'Browse Profiles',
    find_partner: 'Find Partner',
    trusted_platform: 'Trusted Platform',
    all_services: 'All Services',
    view_profile: 'View Profile',
    back: 'Back',
    Islam: 'Islam',
    Hindu: 'Hindu',
    Christian: 'Christian',
    Buddhist: 'Buddhist',
    Other: 'Other',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('bn');

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const toggleLang = () => setLang(prev => prev === 'bn' ? 'en' : 'bn');

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}